package org.bluerays.client;

import java.io.IOException;
import java.util.Date;

import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.bluerays.config.BasicConfiguration;


public class RestClient {

/**
 * 	
 * @param indexName is an  index name in which data get inserted
 * @param type  is used to create multiple distinct  an indexes in single index. 
 * @param source is actual  message which generated by log server
 * @return it return  true if message post successfully.
 */
	public  boolean postMessage(String indexName,String type ,String source){
		
		try {
	
			
			CloseableHttpClient httpClient=HttpClients.createDefault();
			HttpPost httpPost=new HttpPost("http://"+BasicConfiguration.IPV4+":"+BasicConfiguration.HTTP_PORT+"/"+indexName+"/"+type);
			
			StringEntity message=new StringEntity(source);
			message.setContentType("application/json");

			httpPost.setEntity(message);
			CloseableHttpResponse response = httpClient.execute(httpPost);
			
			httpClient.close();
			if(response.getStatusLine() != null){
				if(response.getStatusLine().toString().contains("201"))
				return true;
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return false;
	}
	
	
}
